### ISSUE TITLE
Error while running main.py

### ISSUE THREAD

**Issue by sid209e** [CyberPunkMetalHead/seo-gpt#3]
While running main.py, it shows following error:
Traceback (most recent call last):
  File "/home/sid/seogpt/seo-gpt/main.py", line 6, in <module>
    from utils.logger import *
  File "/home/sid/seogpt/seo-gpt/utils/logger.py", line 4, in <module>
    logging.basicConfig(
  File "/home/sid/miniconda3/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/home/sid/miniconda3/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/sid/miniconda3/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/sid/seogpt/seo-gpt/logs/2023-04-26_log.log'

**Comment by CyberPunkMetalHead** [comment]
It is possible that you have removed the logs file? It shouldn't require it in order to run though. Could you try running through VC Code?
